trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Step 1: Install NuGet
- task: NuGetToolInstaller@1

# Step 2: Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Step 3: Build the solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Step 4: Publish build artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'Build'
    publishLocation: 'Container'

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: 'ddaca74b2abbe962e72f50bd8f7ed8c9'
    apiKey: '9938c9dc742aeee934182e859d8bf3ae243fc68398dca58683176281c6000fe9255d65a5df1948ac27cd0fae104be1f28f34a66afe2e2e296b52a6cd1d7da2c1'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    createProfile: true
    maximumWaitTime: '360'