name: Veracode Upload and Scan

on:
  push:
    branches:
      - main

jobs:
  veracode_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List All Files in Workspace
        run: ls -R ${{ github.workspace }}  # Lists all files for verification

      - name: Build Project
        run: |
          # Adjust this path based on where the .sln or .csproj file is actually located
          dotnet build ${{ github.workspace }}/Verademo-dotnet/Verademo-dotnet.sln --configuration Release

      - name: Veracode Upload and Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "verademo-dotnet"
          createprofile: true
          filepath: "${{ github.workspace }}/bin/Release/net6.0"  # Update if the build output directory differs
          version: "${{ github.run_id }}-${{ github.run_number }}"
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createsandbox: false
          sandboxname: "OptionalSandboxName"
          scantimeout: 120
          deleteincompletescan: true
          debug: true
