name: Veracode Upload and Scan

on:
  push:
    branches:
      - main

jobs:
  veracode_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          # Run your build command; this example uses dotnet build for a .NET project
          dotnet build --configuration Release
          # The build output will typically go to the bin/Release/{framework} directory

      - name: List All Files in Workspace
        run: ls -R ${{ github.workspace }}

      - name: Veracode Upload and Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "verademo-dotnet"
          createprofile: true
          filepath: "${{ github.workspace }}/bin/Release/net6.0"  # Adjust this based on the output of the file listing
          version: "${{ github.run_id }}-${{ github.run_number }}"
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createsandbox: false
          sandboxname: "OptionalSandboxName"
          scantimeout: 120
          deleteincompletescan: true
          debug: true
