name: Veracode Package and Scan

on:
  push:
    branches:
      - main

jobs:
  veracode_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and Install Veracode CLI
        run: |
          mkdir -p veracode-cli
          curl -fsSLo veracode-cli/veracode.zip https://downloads.veracode.com/tools/cli/latest/veracode-cli.zip
          
          # Verify if download was successful
          if [ ! -s veracode-cli/veracode.zip ]; then
            echo "Veracode CLI download failed. Exiting."
            exit 1
          fi

          # Unzip the Veracode CLI and add it to PATH
          unzip veracode-cli/veracode.zip -d veracode-cli || { echo "Unzipping failed"; exit 1; }
          export PATH=$PATH:$PWD/veracode-cli
          echo "Veracode CLI installed in $(pwd)/veracode-cli"

      - name: Verify Veracode CLI Installation
        run: veracode --version

      - name: Configure Veracode CLI
        run: veracode configure --api-id ${{ secrets.VERACODE_API_ID }} --api-key ${{ secrets.VERACODE_API_KEY }}

      - name: Package Application with Veracode Auto-Packager
        run: veracode auto-package --type directory --source ${{ github.workspace }} --output ${{ github.workspace }}/veracode_package.zip

      - name: Upload and Scan
        run: |
          veracode upload --appname "verademo-dotnet" --filepath ${{ github.workspace }}/veracode_package.zip --version "${{ github.run_id }}-${{ github.run_number }}"
          veracode scan --appname "verademo-dotnet" --version "${{ github.run_id }}-${{ github.run_number }}"
