name: Veracode Upload and Scan

on:
  push:
    branches:
      - main

jobs:
  veracode_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          # Replace this with your actual build command
          echo "Building project..."
          # Ensure the build output is in the correct location

      - name: List Files in Compiled Directory
        run: ls -R ${{ github.workspace }}/path/to/your/compiled/code

      - name: Veracode Upload and Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "verademo-dotnet"
          createprofile: true
          filepath: "${{ github.workspace }}/path/to/your/compiled/code"  # Adjust this path to where your compiled files are
          version: "${{ github.run_id }}-${{ github.run_number }}"
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          createsandbox: false
          sandboxname: "OptionalSandboxName"
          scantimeout: 120
          deleteincompletescan: true
          debug: true
