name: Veracode Package and Scan

on:
  push:
    branches:
      - main

jobs:
  veracode_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Veracode CLI
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Configure Veracode CLI
        run: |
          veracode configure --api-id ${{ secrets.VERACODE_API_ID }} --api-key ${{ secrets.VERACODE_API_KEY }}

      - name: Package Application with Veracode Auto-Packager
        run: |
          veracode auto-package --type directory --source ${{ github.workspace }} --output ${{ github.workspace }}/veracode_package.zip

      - name: Upload and Scan
        run: |
          veracode upload --appname "verademo-dotnet" --filepath ${{ github.workspace }}/veracode_package.zip --version "${{ github.run_id }}-${{ github.run_number }}"
          veracode scan --appname "verademo-dotnet" --version "${{ github.run_id }}-${{ github.run_number }}"
